version: '3.9'

services:
  db:
    image: 'postgres:latest'
    ports:
      - '5430:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mini-mail